spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/markentry
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: info
  file:
    name: markentry.log

